# Welcome to Jekyll!

# Website settings
title: Nikhil Vanjani
description: Homepage of Nikhil Vanjani, IIT Kanpur  
keywords: Nikhil,Vanjani,CSE,IITK,Jekyll,anujnag
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://nikhilvanjani.github.io  # url should be changed to 'http://www.jack003.com/homepage' as before
# url: http://127.0.0.1:4000
img_path: ./static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Nikhil Vanjani  # Be used at blog posts' author.
  first_name: Nikhil # Be used at index page about me section.
  last_name: Vanjani # Be used at index page about me section.
  cv: Resume_Nikhil.pdf  # A online CV can be printed as PDF, leave blank if you don't have now
  email: nikhilvanjani61@gmail.com  # Leave blank if you don't have now
  facebook_username: vanjaninikhil  # Leave blank if you don't have now
  github_username: nikhilvanjani  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/DP.jpg  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Hi! This is Nikhil Vanjani, a Masters student at Carnegie Mellon University. I am fortunate to be advised by Dr. Elaine Shi for my masters thesis on functional encryption. I completed my B Tech in Computer Science and Engineering from IIT Kanpur, India in 2018. My research interests are in Cryptography and Blockchains, and I am generally interested in Theoretical Computer Science and Cyber Security.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#  name: jalpc
#  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
    id: UA-92624039-1

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
